language: ruby
rvm:
 - 2.3.1
 - 2.2
 - 2.1
sudo: false
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
language: ruby
cache: bundler
before_install: gem install bundler
bundler_args: --without development
before_script:
  - export RETRY_COUNT=3
  - bin/rake refinery:testing:dummy_app
script:
  - bin/rspec $EXTENSION/spec
env:
  - DB=postgresql
  - DB=mysql
notifications:
  email: true

rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0.0
sudo: false
